<?php
// Liste des pays du monde avec leur nationalité (gentilé) en français, utilisée pour les
// listes déroulantes "Nationalité" et "Pays" du formulaire de pré-inscription. Deux colonnes
// indépendantes : un candidat peut par exemple être de nationalité "Malgache" tout en résidant
// dans un "Pays" différent.
return [
    ['pays' => 'Afghanistan', 'nationalite' => 'Afghane'],
    ['pays' => 'Afrique du Sud', 'nationalite' => 'Sud-Africaine'],
    ['pays' => 'Albanie', 'nationalite' => 'Albanaise'],
    ['pays' => 'Algérie', 'nationalite' => 'Algérienne'],
    ['pays' => 'Allemagne', 'nationalite' => 'Allemande'],
    ['pays' => 'Andorre', 'nationalite' => 'Andorrane'],
    ['pays' => 'Angola', 'nationalite' => 'Angolaise'],
    ['pays' => 'Arabie Saoudite', 'nationalite' => 'Saoudienne'],
    ['pays' => 'Argentine', 'nationalite' => 'Argentine'],
    ['pays' => 'Arménie', 'nationalite' => 'Arménienne'],
    ['pays' => 'Australie', 'nationalite' => 'Australienne'],
    ['pays' => 'Autriche', 'nationalite' => 'Autrichienne'],
    ['pays' => 'Azerbaïdjan', 'nationalite' => 'Azerbaïdjanaise'],
    ['pays' => 'Bahamas', 'nationalite' => 'Bahaméenne'],
    ['pays' => 'Bahreïn', 'nationalite' => 'Bahreïnienne'],
    ['pays' => 'Bangladesh', 'nationalite' => 'Bangladaise'],
    ['pays' => 'Barbade', 'nationalite' => 'Barbadienne'],
    ['pays' => 'Belgique', 'nationalite' => 'Belge'],
    ['pays' => 'Belize', 'nationalite' => 'Bélizienne'],
    ['pays' => 'Bénin', 'nationalite' => 'Béninoise'],
    ['pays' => 'Bhoutan', 'nationalite' => 'Bhoutanaise'],
    ['pays' => 'Biélorussie', 'nationalite' => 'Biélorusse'],
    ['pays' => 'Birmanie (Myanmar)', 'nationalite' => 'Birmane'],
    ['pays' => 'Bolivie', 'nationalite' => 'Bolivienne'],
    ['pays' => 'Bosnie-Herzégovine', 'nationalite' => 'Bosnienne'],
    ['pays' => 'Botswana', 'nationalite' => 'Botswanaise'],
    ['pays' => 'Brésil', 'nationalite' => 'Brésilienne'],
    ['pays' => 'Brunei', 'nationalite' => 'Brunéienne'],
    ['pays' => 'Bulgarie', 'nationalite' => 'Bulgare'],
    ['pays' => 'Burkina Faso', 'nationalite' => 'Burkinabée'],
    ['pays' => 'Burundi', 'nationalite' => 'Burundaise'],
    ['pays' => 'Cambodge', 'nationalite' => 'Cambodgienne'],
    ['pays' => 'Cameroun', 'nationalite' => 'Camerounaise'],
    ['pays' => 'Canada', 'nationalite' => 'Canadienne'],
    ['pays' => 'Cap-Vert', 'nationalite' => 'Cap-Verdienne'],
    ['pays' => 'République Centrafricaine', 'nationalite' => 'Centrafricaine'],
    ['pays' => 'Chili', 'nationalite' => 'Chilienne'],
    ['pays' => 'Chine', 'nationalite' => 'Chinoise'],
    ['pays' => 'Chypre', 'nationalite' => 'Chypriote'],
    ['pays' => 'Colombie', 'nationalite' => 'Colombienne'],
    ['pays' => 'Comores', 'nationalite' => 'Comorienne'],
    ['pays' => 'Congo (Brazzaville)', 'nationalite' => 'Congolaise'],
    ['pays' => 'Congo (RDC)', 'nationalite' => 'Congolaise (RDC)'],
    ['pays' => 'Corée du Nord', 'nationalite' => 'Nord-Coréenne'],
    ['pays' => 'Corée du Sud', 'nationalite' => 'Sud-Coréenne'],
    ['pays' => 'Costa Rica', 'nationalite' => 'Costaricaine'],
    ['pays' => 'Côte d\'Ivoire', 'nationalite' => 'Ivoirienne'],
    ['pays' => 'Croatie', 'nationalite' => 'Croate'],
    ['pays' => 'Cuba', 'nationalite' => 'Cubaine'],
    ['pays' => 'Danemark', 'nationalite' => 'Danoise'],
    ['pays' => 'Djibouti', 'nationalite' => 'Djiboutienne'],
    ['pays' => 'Dominique', 'nationalite' => 'Dominiquaise'],
    ['pays' => 'Égypte', 'nationalite' => 'Égyptienne'],
    ['pays' => 'Émirats Arabes Unis', 'nationalite' => 'Émirienne'],
    ['pays' => 'Équateur', 'nationalite' => 'Équatorienne'],
    ['pays' => 'Érythrée', 'nationalite' => 'Érythréenne'],
    ['pays' => 'Espagne', 'nationalite' => 'Espagnole'],
    ['pays' => 'Estonie', 'nationalite' => 'Estonienne'],
    ['pays' => 'Eswatini', 'nationalite' => 'Swazie'],
    ['pays' => 'États-Unis', 'nationalite' => 'Américaine'],
    ['pays' => 'Éthiopie', 'nationalite' => 'Éthiopienne'],
    ['pays' => 'Fidji', 'nationalite' => 'Fidjienne'],
    ['pays' => 'Finlande', 'nationalite' => 'Finlandaise'],
    ['pays' => 'France', 'nationalite' => 'Française'],
    ['pays' => 'Gabon', 'nationalite' => 'Gabonaise'],
    ['pays' => 'Gambie', 'nationalite' => 'Gambienne'],
    ['pays' => 'Géorgie', 'nationalite' => 'Géorgienne'],
    ['pays' => 'Ghana', 'nationalite' => 'Ghanéenne'],
    ['pays' => 'Grèce', 'nationalite' => 'Grecque'],
    ['pays' => 'Grenade', 'nationalite' => 'Grenadienne'],
    ['pays' => 'Guatemala', 'nationalite' => 'Guatémaltèque'],
    ['pays' => 'Guinée', 'nationalite' => 'Guinéenne'],
    ['pays' => 'Guinée-Bissau', 'nationalite' => 'Bissau-Guinéenne'],
    ['pays' => 'Guinée Équatoriale', 'nationalite' => 'Équato-Guinéenne'],
    ['pays' => 'Guyana', 'nationalite' => 'Guyanienne'],
    ['pays' => 'Haïti', 'nationalite' => 'Haïtienne'],
    ['pays' => 'Honduras', 'nationalite' => 'Hondurienne'],
    ['pays' => 'Hongrie', 'nationalite' => 'Hongroise'],
    ['pays' => 'Inde', 'nationalite' => 'Indienne'],
    ['pays' => 'Indonésie', 'nationalite' => 'Indonésienne'],
    ['pays' => 'Irak', 'nationalite' => 'Irakienne'],
    ['pays' => 'Iran', 'nationalite' => 'Iranienne'],
    ['pays' => 'Irlande', 'nationalite' => 'Irlandaise'],
    ['pays' => 'Islande', 'nationalite' => 'Islandaise'],
    ['pays' => 'Israël', 'nationalite' => 'Israélienne'],
    ['pays' => 'Italie', 'nationalite' => 'Italienne'],
    ['pays' => 'Jamaïque', 'nationalite' => 'Jamaïcaine'],
    ['pays' => 'Japon', 'nationalite' => 'Japonaise'],
    ['pays' => 'Jordanie', 'nationalite' => 'Jordanienne'],
    ['pays' => 'Kazakhstan', 'nationalite' => 'Kazakhe'],
    ['pays' => 'Kenya', 'nationalite' => 'Kényane'],
    ['pays' => 'Kirghizistan', 'nationalite' => 'Kirghize'],
    ['pays' => 'Kiribati', 'nationalite' => 'Kiribatienne'],
    ['pays' => 'Kosovo', 'nationalite' => 'Kosovare'],
    ['pays' => 'Koweït', 'nationalite' => 'Koweïtienne'],
    ['pays' => 'Laos', 'nationalite' => 'Laotienne'],
    ['pays' => 'Lesotho', 'nationalite' => 'Lésothane'],
    ['pays' => 'Lettonie', 'nationalite' => 'Lettone'],
    ['pays' => 'Liban', 'nationalite' => 'Libanaise'],
    ['pays' => 'Liberia', 'nationalite' => 'Libérienne'],
    ['pays' => 'Libye', 'nationalite' => 'Libyenne'],
    ['pays' => 'Liechtenstein', 'nationalite' => 'Liechtensteinoise'],
    ['pays' => 'Lituanie', 'nationalite' => 'Lituanienne'],
    ['pays' => 'Luxembourg', 'nationalite' => 'Luxembourgeoise'],
    ['pays' => 'Macédoine du Nord', 'nationalite' => 'Macédonienne'],
    ['pays' => 'Madagascar', 'nationalite' => 'Malgache'],
    ['pays' => 'Malaisie', 'nationalite' => 'Malaisienne'],
    ['pays' => 'Malawi', 'nationalite' => 'Malawite'],
    ['pays' => 'Maldives', 'nationalite' => 'Maldivienne'],
    ['pays' => 'Mali', 'nationalite' => 'Malienne'],
    ['pays' => 'Malte', 'nationalite' => 'Maltaise'],
    ['pays' => 'Maroc', 'nationalite' => 'Marocaine'],
    ['pays' => 'Îles Marshall', 'nationalite' => 'Marshallaise'],
    ['pays' => 'Maurice', 'nationalite' => 'Mauricienne'],
    ['pays' => 'Mauritanie', 'nationalite' => 'Mauritanienne'],
    ['pays' => 'Mexique', 'nationalite' => 'Mexicaine'],
    ['pays' => 'Micronésie', 'nationalite' => 'Micronésienne'],
    ['pays' => 'Moldavie', 'nationalite' => 'Moldave'],
    ['pays' => 'Monaco', 'nationalite' => 'Monégasque'],
    ['pays' => 'Mongolie', 'nationalite' => 'Mongole'],
    ['pays' => 'Monténégro', 'nationalite' => 'Monténégrine'],
    ['pays' => 'Mozambique', 'nationalite' => 'Mozambicaine'],
    ['pays' => 'Namibie', 'nationalite' => 'Namibienne'],
    ['pays' => 'Nauru', 'nationalite' => 'Nauruane'],
    ['pays' => 'Népal', 'nationalite' => 'Népalaise'],
    ['pays' => 'Nicaragua', 'nationalite' => 'Nicaraguayenne'],
    ['pays' => 'Niger', 'nationalite' => 'Nigérienne'],
    ['pays' => 'Nigeria', 'nationalite' => 'Nigériane'],
    ['pays' => 'Norvège', 'nationalite' => 'Norvégienne'],
    ['pays' => 'Nouvelle-Zélande', 'nationalite' => 'Néo-Zélandaise'],
    ['pays' => 'Oman', 'nationalite' => 'Omanaise'],
    ['pays' => 'Ouganda', 'nationalite' => 'Ougandaise'],
    ['pays' => 'Ouzbékistan', 'nationalite' => 'Ouzbèke'],
    ['pays' => 'Pakistan', 'nationalite' => 'Pakistanaise'],
    ['pays' => 'Palaos', 'nationalite' => 'Palaosienne'],
    ['pays' => 'Palestine', 'nationalite' => 'Palestinienne'],
    ['pays' => 'Panama', 'nationalite' => 'Panaméenne'],
    ['pays' => 'Papouasie-Nouvelle-Guinée', 'nationalite' => 'Papouasienne'],
    ['pays' => 'Paraguay', 'nationalite' => 'Paraguayenne'],
    ['pays' => 'Pays-Bas', 'nationalite' => 'Néerlandaise'],
    ['pays' => 'Pérou', 'nationalite' => 'Péruvienne'],
    ['pays' => 'Philippines', 'nationalite' => 'Philippine'],
    ['pays' => 'Pologne', 'nationalite' => 'Polonaise'],
    ['pays' => 'Portugal', 'nationalite' => 'Portugaise'],
    ['pays' => 'Qatar', 'nationalite' => 'Qatarienne'],
    ['pays' => 'Roumanie', 'nationalite' => 'Roumaine'],
    ['pays' => 'Royaume-Uni', 'nationalite' => 'Britannique'],
    ['pays' => 'Russie', 'nationalite' => 'Russe'],
    ['pays' => 'Rwanda', 'nationalite' => 'Rwandaise'],
    ['pays' => 'Saint-Christophe-et-Niévès', 'nationalite' => 'Kittitienne'],
    ['pays' => 'Saint-Marin', 'nationalite' => 'Saint-Marinaise'],
    ['pays' => 'Saint-Vincent-et-les-Grenadines', 'nationalite' => 'Vincentaise'],
    ['pays' => 'Sainte-Lucie', 'nationalite' => 'Saint-Lucienne'],
    ['pays' => 'Salomon', 'nationalite' => 'Salomonaise'],
    ['pays' => 'Salvador', 'nationalite' => 'Salvadorienne'],
    ['pays' => 'Samoa', 'nationalite' => 'Samoane'],
    ['pays' => 'Sao Tomé-et-Principe', 'nationalite' => 'Santoméenne'],
    ['pays' => 'Sénégal', 'nationalite' => 'Sénégalaise'],
    ['pays' => 'Serbie', 'nationalite' => 'Serbe'],
    ['pays' => 'Seychelles', 'nationalite' => 'Seychelloise'],
    ['pays' => 'Sierra Leone', 'nationalite' => 'Sierra-Léonaise'],
    ['pays' => 'Singapour', 'nationalite' => 'Singapourienne'],
    ['pays' => 'Slovaquie', 'nationalite' => 'Slovaque'],
    ['pays' => 'Slovénie', 'nationalite' => 'Slovène'],
    ['pays' => 'Somalie', 'nationalite' => 'Somalienne'],
    ['pays' => 'Soudan', 'nationalite' => 'Soudanaise'],
    ['pays' => 'Soudan du Sud', 'nationalite' => 'Sud-Soudanaise'],
    ['pays' => 'Sri Lanka', 'nationalite' => 'Sri-Lankaise'],
    ['pays' => 'Suède', 'nationalite' => 'Suédoise'],
    ['pays' => 'Suisse', 'nationalite' => 'Suisse'],
    ['pays' => 'Suriname', 'nationalite' => 'Surinamaise'],
    ['pays' => 'Syrie', 'nationalite' => 'Syrienne'],
    ['pays' => 'Tadjikistan', 'nationalite' => 'Tadjike'],
    ['pays' => 'Tanzanie', 'nationalite' => 'Tanzanienne'],
    ['pays' => 'Tchad', 'nationalite' => 'Tchadienne'],
    ['pays' => 'Tchéquie', 'nationalite' => 'Tchèque'],
    ['pays' => 'Thaïlande', 'nationalite' => 'Thaïlandaise'],
    ['pays' => 'Timor Oriental', 'nationalite' => 'Est-Timoraise'],
    ['pays' => 'Togo', 'nationalite' => 'Togolaise'],
    ['pays' => 'Tonga', 'nationalite' => 'Tonguienne'],
    ['pays' => 'Trinité-et-Tobago', 'nationalite' => 'Trinidadienne'],
    ['pays' => 'Tunisie', 'nationalite' => 'Tunisienne'],
    ['pays' => 'Turkménistan', 'nationalite' => 'Turkmène'],
    ['pays' => 'Turquie', 'nationalite' => 'Turque'],
    ['pays' => 'Tuvalu', 'nationalite' => 'Tuvaluane'],
    ['pays' => 'Ukraine', 'nationalite' => 'Ukrainienne'],
    ['pays' => 'Uruguay', 'nationalite' => 'Uruguayenne'],
    ['pays' => 'Vanuatu', 'nationalite' => 'Vanuatuane'],
    ['pays' => 'Vatican', 'nationalite' => 'Vaticane'],
    ['pays' => 'Venezuela', 'nationalite' => 'Vénézuélienne'],
    ['pays' => 'Vietnam', 'nationalite' => 'Vietnamienne'],
    ['pays' => 'Yémen', 'nationalite' => 'Yéménite'],
    ['pays' => 'Zambie', 'nationalite' => 'Zambienne'],
    ['pays' => 'Zimbabwe', 'nationalite' => 'Zimbabwéenne'],
    ['pays' => 'Autre', 'nationalite' => 'Autre'],
];
